### ISSUE TITLE
Alert when entering wrong credentials should be more user friendly

### ISSUE THREAD

**Issue by boetter** [olegam/Postboks#10]
Used to work just fine, but in the latest version I get this error when trying to add my account:

<img width="420" alt="screen shot 2016-01-05 at 10 38 00" src="https://cloud.githubusercontent.com/assets/1336222/12111809/7a10560a-b398-11e5-90fb-50298e147f0a.png">

**Comment by olegam** [comment]
Works for me. Are you sure both codes are correct and you didn't swap them?

**Comment by watson** [comment]
I got the same error when I accidentally entered the wrong CPR number

**Comment by olegam** [comment]
The text should be changed to something more friendly. Explaining that the credentials could not be validated.

**Comment by olegam** [comment]
@sebreh could you help with a Swedish translation here? https://github.com/olegam/Postboks/blob/bf8126c973d160afd810a9313f143aea62a6a522/Postboks/sv.lproj/Localizable.strings#L33 ?

**Comment by boetter** [comment]
I figured out why it gave me an error!

When entering social security number I entered XXXXX-XXXX, it accepted when I did it as XXXXXXXXXX

**Comment by olegam** [comment]
Ahh right. We should remove non-numeric characters from the input.

**Comment by olegam** [comment]
I created a new issue for this: https://github.com/olegam/Postboks/issues/27
