### ISSUE TITLE
laggy first sync.

### ISSUE THREAD

**Issue by klh** [olegam/Postboks#11]
don't create folders unless documents have been uploaded.
you're looping through the dates and creating empty folder...would be less intrusive to just add a folder when data is present: 
![image](https://cloud.githubusercontent.com/assets/596813/12114406/da13a23a-b3a9-11e5-89e4-1ffb066057c4.png)

**Comment by olegam** [comment]
As I remember data will be present for every folder. If the folder is empty it just hasn't finished downloading yet. Right?

**Comment by klh** [comment]
true, but the hit of creating all the folders at once on first run just kills the app.
meaning that your blankslate experience is a laggy and stalled app untill all folders are created.

**Comment by olegam** [comment]
All syncing is done asynchronously so the app should not be unresponsive or laggy while syncing the first time. It may not be clear to the user why the folders are still empty but that is something else. The status label in the manu bar already says "Syncing...".
