### ISSUE TITLE
Sync -> Failed -> Sync loop

### ISSUE THREAD

**Issue by perlausten** [olegam/Postboks#14]
Hi Ole, great app.

On my machine the app has gone into a loop where it continuously syncs, fails, syncs, fails etc. Sync followed by "Failed" takes place every 2 seconds approximately (and 15-20% CPU).

The app has synced lots of items with success.

Is there a log somewhere that can help pinpoint the problem?

**Comment by olegam** [comment]
Thanks Per. Sounds weird. You can try looking in the system console app. If you post the entries here from Postboks that may be useful for figuring out what is wrong.

**Comment by perlausten** [comment]
This might explain it :smiley: 

```
Jan  7 08:45:59 PHL-Consult-Per-Henrik-Lausten Postboks[88125]: Starting download for user xxxxxxxxxx
Jan  7 08:46:00 PHL-Consult-Per-Henrik-Lausten Postboks[88125]: <RACDynamicSignal: 0x7faf2342db10> name:  error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7faf233031b0> { URL: https://rest.e-boks.dk/mobile/1/xml.svc/en-gb/13660/0/mail/folder/0/message/2014A10A09A00B06B17B132559/content } { status code: 500, headers {
Jan  7 08:46:00 PHL-Consult-Per-Henrik-Lausten Postboks[88125]: Error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7faf233031b0> { URL: https://rest.e-boks.dk/mobile/1/xml.svc/en-gb/13660/0/mail/folder/0/message/2014A10A09A00B06B17B132559/content } { status code: 500, headers {
````

**Comment by olegam** [comment]
Maybe something special about your account or one of your documents. You could try inspecting the requests and responses with Charles Web Proxy.

**Comment by olegam** [comment]
Did you get any closer to figuring out what is wrong? If you send me (use email or sanitize first as the request contains your credentials) a capture of the request/response from Charles I can take a look.

**Comment by perlausten** [comment]
I have sent you a log from Charles. Thanks.

**Comment by olegam** [comment]
From the request/response log it seems the app is just trying to get the content of some documents and then the server returns error 500. We could ignore this error and let the sync process succeed. Then it should still retry in the next hour...

**Comment by perlausten** [comment]
I agree with your analysis and your suggested solution.

**Comment by larsenpedersen** [comment]
I'm experiencing the same issue in the current version (0.6.0 (29)) - and only a very small amount of documents are synching.

**Comment by olegam** [comment]
@larsenpedersen maybe you can come by my place or office some day and we can look at the problem together using your account? It's really difficult for me since I can't reproduce the issue myself.

**Comment by larsenpedersen** [comment]
@olegam Sure thing! I'll just drop you an e-mail for now :)
