### ISSUE TITLE
A more flat file structure

### ISSUE THREAD

**Issue by larsenwork** [olegam/Postboks#22]
Could be cool if there was an option to do this:

```
eboks-folder/YYYY-MM-DD-filename.pdf
```

and/or this

```
eboks-folder/CPR#/YYYY-MM-DD-filename.pdf
```

instead of current

```
eboks-folder/CPR#/YYYY-MM/filename.pdf
```

**Comment by danchr** [comment]
Personally, I'd prefer something like this:

`e-Boks/Sender/filename.pdf`

The primary complication is that some senders heavily reuse subjects but we'd have to address that anyway — see issue #29.

**Comment by olegam** [comment]
It seems there are many different views one what the nicest file structure should be and supporting multiple would be challenging. I would rather have a new UI view that lets users find documents more easily by providing sorting, filtering and searching capabilities. If anyone is up for designing or implementing such a view let me know and I can help you.
