### ISSUE TITLE
Attachments doesn't download

### ISSUE THREAD

**Issue by fth1963** [olegam/Postboks#24]
Some E-boks documents has an attachement (Bilag). The attachments are not downloaded at all.

**Comment by christianhaargaard** [comment]
I had the same experience. I don't know if it is a functionatily that is easy to incorporate, but otherwise you might want to mention this in the readme.

**Comment by olegam** [comment]
I would like to take a look at this but I can't as I don't have any of those documents on my account.

**Comment by fth1963** [comment]
Examples of companies using attachments in E-boks from time to time: domstol.dk (Tinglysning), statsforvaltning, Københavns kommune. Maybe you know some one receiving from those.

**Comment by olegam** [comment]
Turns out I actually have a message from Københavns Kommune with attachments:) Started working on support for this on this branch: https://github.com/olegam/Postboks/tree/feature/attachments-support ...not ready yet but getting there.

**Comment by christianhaargaard** [comment]
Wow, I'm impressed how fast you got started on this feature!

Also, cudos for actually making eboks easy to use.

**Comment by olegam** [comment]
It's working now: https://github.com/olegam/Postboks/pull/25
Could use some testing

**Comment by christianhaargaard** [comment]
I wanted to test it, but it appears that my system is not setup properly
for building it. Any chance you could supply a binary?

**Comment by olegam** [comment]
I made a pre-release build. Please test if this works for you and if it causes any other issues: https://github.com/olegam/Postboks/releases/tag/v0.5.0b28

You need to empty the documents folder to make a full sync and make attachments download.

**Comment by christianhaargaard** [comment]
Hello Ole,

The pre-release runs fine on my system and correctly downloads attachments.
I had one idea though. Would it make sense to indicate in the filenames
when the file is an attachment?
The current scheme (attacments of <xxx> is called <xxx -
attachmentfilename>) makes sense if you know that attachments exist, less
if you don't know about this feature on eboks. Perhaps something along the
linen <xxx-attachment: filename>. Just a quick thought :-)

Thanks for including this feature so quickly!
