### ISSUE TITLE
Handle filename conflicts gracefully

### ISSUE THREAD

**Issue by danchr** [olegam/Postboks#29]
In order to be able to rely on Postboks for downloading documents from e-Boks, it's crucial that *all* documents *always* get downloaded. At the moment, that's not the case: Postboks silently discards any messages using if they duplicate the sender and subject of a previous message that month. Some public departments don't use the subject field, so this is, in fact, quite possible.

**Comment by olegam** [comment]
Right... I suggest we postfix the filename with some unique id like this:
`[sender name] - [subject] (ABC1234).pdf`

The e-Boks API already assigns some identifier to each message, but it is quite long. So I suggest we hash that and take first 5 chars of the hexadecimal representation. That would look more user friendly.

If anyone is up for this tasks I would be happy to help.

Regarding migration I think it is fair we prompt the user to remove all current files and do a fresh sync. So  that should be simple to do.

**Comment by danchr** [comment]
Actually, you could just store it in an extended attribute. That should achieve the same results without cluttering the filename even further.

**Comment by olegam** [comment]
How would the filename then be unique?

**Comment by danchr** [comment]
You'd just add a suffix, e.g. ‘2’ 😊

**Comment by danchr** [comment]
Alternatively, you *could* just assume that messages never go away, and determine upfront that the first message always uses the full name, and the second one ‘X 2.pdf’, and so on. Of course, that also assumes that we always get a full list of messages in every request; is that the case?

**Comment by olegam** [comment]
The sync mechanism relies on files existing already don't need to be downloaded again. And files can go away. So I don't think that is an option.

Storing the message identifier in an extended attribute could work. But it is not as simple as I would prefer...

**Comment by danchr** [comment]
Well, at least setting an extended attribute is borderline trivial —  I wrote the code to do so as part of a [bit of hacking](https://gist.github.com/danchr/d47fe3a77025464f6520ee4131ca975e) on Postboks.

**Comment by olegam** [comment]
I included a simple solution for this issue in https://github.com/olegam/Postboks/pull/28
